import test from 'node:test';import assert from 'node:assert/strict';import {createFlightReport,reportCsv,type ReportRecord} from '../lib/reports/flight-report';import type {EquipmentAlias} from '../lib/domain/equipment-identity';
test('consolidated reports include historical identities once without rewriting rows or costs',()=>{
 const records:ReportRecord[]=[{kind:'asset',id:'old',revision:1,data:{name:'Old',category:'Aircraft'}},{kind:'asset',id:'keep',revision:2,data:{name:'Keep',category:'Aircraft'}},...['old','keep'].map((id,i)=>({kind:'flight',id:'f'+i,revision:1,data:{date:'2026-09-07',aircraftId:id,equipmentIds:['old','keep'],aircraft:id,pilot:'Pilot',durationSeconds:60,distance:1}})),{kind:'service',id:'job',revision:1,data:{targetKind:'asset',targetId:'old',task:'Original inspection',status:'Completed',completedAt:'2026-09-07',cost:12.5,currency:'AED'}}];
 const aliases:EquipmentAlias[]=[{kind:'asset',source_id:'old',canonical_id:'keep'}];const original=JSON.stringify(records),request={type:'Aircraft' as const,entityId:'keep',from:'2026-09-01',to:'2026-09-30',includeHistory:true};
 const legacy=createFlightReport(request,records,[]),report=createFlightReport(request,records,[],aliases);
 assert.equal(legacy.flightCount,1);assert.equal(legacy.version,1);assert.equal(report.version,2);assert.equal(report.flightCount,2);assert.equal(report.durationSeconds,120);assert.equal(report.rows[0][7],'old');assert.equal(report.history?.rows[0][3],'job');assert.equal(report.history?.rows[0][7],12.5);assert.equal(JSON.stringify(records),original);assert.match(reportCsv(report,'QA','2026-09-07'),/Consolidated equipment family/);
});
test('battery family reports include source readings with typed identity isolation',()=>{
 const records:ReportRecord[]=[{kind:'battery',id:'a',revision:1,data:{model:'Old'}},{kind:'battery',id:'b',revision:1,data:{model:'New'}},{kind:'flight',id:'f',revision:1,data:{battery:'a',batteryIds:['a','b'],date:'2026-09-07',durationSeconds:60,distance:0,pilot:'P',aircraft:'D'}},{kind:'battery_reading',id:'r',revision:1,data:{batteryId:'a',measuredAt:'2026-09-07T00:00:00Z',deviceCycles:40}},{kind:'service',id:'wrong',revision:1,data:{targetKind:'asset',targetId:'a',due:'2026-09-07'}}];
 const report=createFlightReport({type:'Battery',entityId:'b',from:'2026-09-01',to:'2026-09-30',includeHistory:true},records,[],[{kind:'battery',source_id:'a',canonical_id:'b'}]);assert.equal(report.flightCount,1);assert.equal(report.history?.rows.length,1);assert.equal(report.history?.rows[0][3],'r');
});
