'use client';
import {useState} from 'react';import {useApp} from './app-provider';import {Button} from '@/components/ui/button';import {equipmentMergeReview} from '@/lib/operations/equipment-merge-review';
export default function EquipmentMergeReview(){
 const app=useApp(),[kind,setKind]=useState<'asset'|'battery'>('asset'),[keep,setKeep]=useState(''),[duplicate,setDuplicate]=useState(''),[review,setReview]=useState<ReturnType<typeof equipmentMergeReview>|null>(null),[error,setError]=useState('');
 if(!['admin','manager'].includes(app.profile.role))return null;
 const items=app.records.filter(r=>r.kind===kind);
 return <details className="glass equipment-bulk-editor"><summary>Review possible inventory duplicates</summary><p>Compare identities, counters and linked records before consolidation. This review does not merge or delete equipment; applying a merge is not available yet.</p>
 <div className="form-grid"><label className="field">Equipment kind<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setKeep('');setDuplicate('');setReview(null)}}><option value="asset">Aircraft / equipment</option><option value="battery">Batteries</option></select></label>{[['Keep record',keep,setKeep],['Possible duplicate',duplicate,setDuplicate]].map(([label,value,setter])=><label key={String(label)} className="field">{String(label)}<select value={String(value)} onChange={e=>{(setter as typeof setKeep)(e.target.value);setReview(null)}}><option value="">Choose…</option>{items.map(r=><option key={r.id} value={r.id}>{r.data.name||r.data.sourceName||r.data.model||r.id} · {r.data.serial||r.id}</option>)}</select></label>)}</div>
 <Button variant="outline" disabled={!keep||!duplicate||keep===duplicate} onClick={()=>{try{setReview(equipmentMergeReview(app.records,{kind,id:keep},{kind,id:duplicate}));setError('')}catch(e){setError((e as Error).message)}}}>Compare records</Button>{error&&<p role="alert">{error}</p>}
 {review&&<><p>{review.conflicts.length?review.conflicts.join(' · '):'No category or recorded-serial conflict detected. This does not prove these are the same physical item.'}</p><div className="report-table-scroll" role="region" aria-label="Equipment merge differences" tabIndex={0}><table><thead><tr><th>Field</th><th>Keep record</th><th>Possible duplicate</th></tr></thead><tbody>{review.differences.map(r=><tr key={r.field}><th scope="row">{r.field}</th><td>{r.keep==null?'Not recorded':String(r.keep)}</td><td>{r.duplicate==null?'Not recorded':String(r.duplicate)}</td></tr>)}</tbody></table></div>
 <p>Usage counters must be reconciled explicitly; they are never added together by this review. Submitted mission packages and signed history must retain their original source identity.</p>
 {[['Keep record',review.keepReferences],['Possible duplicate',review.duplicateReferences]].map(([label,refs])=><details key={String(label)}><summary>{String(label)} · {(refs as any[]).length} linked records</summary><div className="kit-candidates">{(refs as any[]).map(r=><p key={r.kind+':'+r.id}>{r.kind} · {r.name}<small>{r.id} · revision {r.revision} · {r.status}</small></p>)}</div></details>)}
 <p className="fine-print">This is a snapshot of loaded organization records. Saved report snapshots, external shares and any unknown legacy relationships still require server-side review before a merge can be applied.</p></>}
 </details>;
}
