'use client';
import {useState} from 'react';import {useApp} from './app-provider';import {Button} from '@/components/ui/button';import {equipmentMergeReview} from '@/lib/operations/equipment-merge-review';
import {api} from '@/lib/supabase-browser';
export default function EquipmentMergeReview(){
 const app=useApp(),[kind,setKind]=useState<'asset'|'battery'>('asset'),[keep,setKeep]=useState(''),[duplicate,setDuplicate]=useState(''),[review,setReview]=useState<(ReturnType<typeof equipmentMergeReview>&{reportReferences:any[];shareReferences:any[];capturedAt:string;reviewHash:string})|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(!['admin','manager'].includes(app.profile.role))return null;
 const items=app.records.filter(r=>r.kind===kind);
 return <details className="glass equipment-bulk-editor"><summary>Review possible inventory duplicates</summary><p>Compare identities, counters and linked records before consolidation. This review does not merge or delete equipment; applying a merge is not available yet.</p>
 <div className="form-grid"><label className="field">Equipment kind<select disabled={busy} value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setKeep('');setDuplicate('');setReview(null)}}><option value="asset">Aircraft / equipment</option><option value="battery">Batteries</option></select></label>{[['Keep record',keep,setKeep],['Possible duplicate',duplicate,setDuplicate]].map(([label,value,setter])=><label key={String(label)} className="field">{String(label)}<select disabled={busy} value={String(value)} onChange={e=>{(setter as typeof setKeep)(e.target.value);setReview(null)}}><option value="">Choose…</option>{items.map(r=><option key={r.id} value={r.id}>{r.data.name||r.data.sourceName||r.data.model||r.id} · {r.data.serial||r.id}</option>)}</select></label>)}</div>
 <Button variant="outline" disabled={busy||!keep||!duplicate||keep===duplicate} onClick={async()=>{setBusy(true);setReview(null);try{setReview(await api('equipment-merge-review',{method:'POST',body:JSON.stringify({kind,keepId:keep,duplicateId:duplicate})}));setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Reviewing server records…':'Compare records'}</Button>{error&&<p role="alert">{error}</p>}
 {review&&<><p>{review.conflicts.length?review.conflicts.join(' · '):'No category or recorded-serial conflict detected. This does not prove these are the same physical item.'}</p><div className="report-table-scroll" role="region" aria-label="Equipment merge differences" tabIndex={0}><table><thead><tr><th>Field</th><th>Keep record</th><th>Possible duplicate</th></tr></thead><tbody>{review.differences.map(r=><tr key={r.field}><th scope="row">{r.field}</th><td>{r.keep==null?'Not recorded':String(r.keep)}</td><td>{r.duplicate==null?'Not recorded':String(r.duplicate)}</td></tr>)}</tbody></table></div>
 <p>Usage counters must be reconciled explicitly; they are never added together by this review. Submitted mission packages and signed history must retain their original source identity.</p>
 {[['Keep record',review.keepReferences],['Possible duplicate',review.duplicateReferences]].map(([label,refs])=><details key={String(label)}><summary>{String(label)} · {(refs as any[]).length} linked records</summary><div className="kit-candidates">{(refs as any[]).map(r=><p key={r.kind+':'+r.id}>{r.kind} · {r.name}<small>{r.id} · revision {r.revision} · {r.status}</small></p>)}</div></details>)}
 <details><summary>{review.reportReferences.length} saved report snapshots potentially referencing these IDs</summary>{review.reportReferences.map(r=><p key={r.id}>{r.request.type} · {r.status} · {r.id}</p>)}</details>
 <details><summary>{review.shareReferences.length} equipment-sharing relationships</summary>{review.shareReferences.map(r=><p key={r.id}>{r.equipmentId} · {r.status} · recipient {r.recipientOrg}</p>)}</details>
 <p className="fine-print">Server snapshot: {review.capturedAt}. Equipment revisions: {review.keep.revision} / {review.duplicate.revision}. Saved report matches are conservative ID matches, not permission to rewrite exports. Unknown legacy relationships and counter reconciliation remain part of merge execution review.</p></>}
 </details>;
}
